# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "83c96f6771437a630b26369b24fd12ee"
name = "Lexor Media"
application_url = "https://lexor-media.onrender.com"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-04"

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/scopes_update"
  topics = [ "app/scopes_update" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/uninstalled"
  topics = [ "app/uninstalled" ]

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_files,write_files,write_products"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [
  "https://lexor-media.onrender.com/api/auth",
  "https://lexor-media.onrender.com/auth/callback",
  "https://lexor-media.onrender.com/auth/shopify/callback",
  "https://lexor-media.onrender.com/api/auth/callback"
]
